services:
  booking_backend_service:
    container_name: 'booking_backend'
    build:
      context: .
    networks:
      - booking_network
    env_file:
    - .env


  booking_celery_worker_service:
    container_name: 'booking_celery_worker'
    build:
      context: .
    networks:
      - booking_network
    env_file:
    - .env
    command: "celery --app=src.tasks.celery_app:task_queue worker -l INFO"


  booking_celery_beat_service:
    container_name: 'booking_celery_beat'
    build:
      context: .
    networks:
      - booking_network
    env_file:
    - .env
    command: "celery --app=src.tasks.celery_app:task_queue beat -l INFO"

networks:
  booking_network:
    external: true